server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huanxu20011572/spring-cloud-config-repo
          username: 40396013@qq.com
          password: qmgps2008
        health:
          repositories:
            a-foo: 
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev
