server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
           uri: https://github.com/huanxu20011572/spring-cloud-config-repo
           # 配置Git仓库的地址
           username: 40396013@qq.com
           # Git仓库的账号
           password: qmgps2008:
           # Git仓库的密码
security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: user                  # 配置登录的账号是user
    password: password123       # 配置登录的密码是password123