server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://10.44.26.19:3306/springclouddb
   username: root
   password: Root!2018 #Qmgps2008@123
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.44.26.22:8761/eureka/
  instance:
    prefer-ip-address: true